apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sit-bmw-oemweb
  namespace: sit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sit-bmw-oemweb
    spec:
      containers:
        - name: sit-bmw-oemweb
          image: registry.cn-beijing.aliyuncs.com/bmwpoc/sit-bmw-oemweb:{version}
          ports:
            - name: http-port
              containerPort: 8080
      imagePullSecrets:
        - name: bmwpoc