apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uat-bmw-oemweb
  namespace: uat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uat-bmw-oemweb
    spec:
      containers:
        - name: uat-bmw-oemweb
          image: registry.cn-beijing.aliyuncs.com/bmwpoc/uat-bmw-oemweb:{version}
          ports:
            - name: http-port
              containerPort: 8080
      imagePullSecrets:
        - name: bmwpoc